services:
  postgres:
    image: postgres:16
    container_name: gigbit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gigbit
      POSTGRES_PASSWORD: gigbit
      POSTGRES_DB: gigbit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./web/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  redis:
    image: redis:7
    container_name: gigbit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./web/backend/api
    container_name: gigbit-api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 4000
      JWT_SECRET: replace-with-strong-secret-please-change-1234
      DATABASE_URL: postgres://gigbit:gigbit@postgres:5432/gigbit
      REDIS_URL: redis://redis:6379
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: gigbitverify@gmail.com
      SMTP_PASS: djfxapxgziqplars
      SMTP_FROM: GigBit <gigbitverify@gmail.com>
      OTP_IN_RESPONSE: "true"

      ADMIN_API_KEY: gigbit-admin-dev-key
    ports:
      - "4000:4000"

volumes:
  postgres_data:
  redis_data:
